server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: bank-cards
  datasource:
    url: jdbc:postgresql://localhost:5432/${bank-cards.datasource.db}
    username: ${bank-cards.datasource.username}
    password: ${bank-cards.datasource.password}
    hikari:
      schema: bank_cards
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    change-log: ./db/migration/changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: ALWAYS


bank-cards:
  valid-period:
    min-months: 1
    max-months: 60
  security:
    jwt-expires-in-minutes: 120
    cors-urls:
      - "http://localhost:8080"
    cors-methods:
      - "GET"
      - "POST"
      - "PATCH"
      - "DELETE"
    cors-headers:
      - "*"
  scheduler:
    expired-cards-update-status:
      cron: "1 0 0 1 * *"

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs