server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: bank-cards
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: bank_cards
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema};
  liquibase:
    change-log: ./db/migration/changelog-master.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: ALWAYS